# Generated by Django 3.0.4 on 2020-04-08 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20200408_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='donation',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number'),
        ),
    ]
