# Generated by Django 3.0.4 on 2020-04-05 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(choices=[('A', 'CLASS A'), ('B', 'CLASS B'), ('C', 'CLASS C'), ('D', 'CLASS D'), ('E', 'CLASS E')], default='A', max_length=80, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grade',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(choices=[('A', 'CLASS A'), ('B', 'CLASS B'), ('C', 'CLASS C'), ('D', 'CLASS D'), ('E', 'CLASS E')], default='A', max_length=80, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rate',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('fee_class', models.SlugField(choices=[('FLAT', 'FLAT'), ('LEVEL', 'LEVEL')], default='FLAT', max_length=80, verbose_name='fee class')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to='django_referrals.Referral', verbose_name='Up Line')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referral',
                'unique_together': {('parent', 'account')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(choices=[('A', 'RULE A'), ('B', 'RULE B'), ('C', 'RULE C'), ('D', 'RULE D'), ('E', 'RULE E')], default='A', max_length=80, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('weighting', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rule',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('flow', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3, verbose_name='Flow')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount')),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Old Balance')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_referrals.referraltransaction_set+', to='contenttypes.ContentType')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_referrals.Referral', verbose_name='Referral')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000000000)])),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000000000)])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_referrals.Grade', verbose_name='Grade')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_referrals.Rule', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Grade Rule',
                'verbose_name_plural': 'Grade Rules',
                'ordering': ['rule__slug'],
                'unique_together': {('grade', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='GradeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('fee_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_referrals.Grade', verbose_name='Grade')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_referrals.Rate', verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Grade Rate',
                'verbose_name_plural': 'Grade Rates',
                'ordering': ['rate__slug'],
                'unique_together': {('grade', 'rate')},
            },
        ),
    ]
