# Generated by Django 3.0.5 on 2020-04-07 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('flow', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3, verbose_name='Flow')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fee Rate')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fee')),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Old Balance')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='reference type')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_referrals.Referral', verbose_name='Referral')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReferralTransaction',
        ),
    ]
